### ISSUE TITLE
Hi! Is this compatible with Sparse Structures?

### ISSUE THREAD

**Issue by makumaku1974** [Caesius-Leo/Deadly_Deadly_Dungeon_Feedback#1]
This i only needed when the datapack structure are frequently spammed in a new world.

**Comment by Caesius-Leo** [comment]
Hi! Yes it's compatible! Do you think I should reduce the dungeon spawn rate?

**Comment by makumaku1974** [comment]
Please do, a customizable config would be nice so I could adjust to my liking.

**Comment by Caesius-Leo** [comment]
Ok I'm working on the generation rate :) for the config idk if it's possible with datapacks, but I'll try if possible

**Comment by makumaku1974** [comment]
> Ok I'm working on the generation rate :) for the config idk if it's possible with datapacks, but I'll try if possible

isnt this packaged as a mod?

**Comment by Caesius-Leo** [comment]
yes there is the mod version and the datapack version

**Comment by makumaku1974** [comment]
okay im downloading the mod version

**Comment by Caesius-Leo** [comment]
ok, have fun :) use sparce structures for now I'll do an update asap

**Comment by Caesius-Leo** [comment]
You can do also like this: open the folder of the mod/datapack and go to data/ddd/worldgen/structure_set. Here you can edit "dddungeons" and "dddtowers" as you like

**Comment by makumaku1974** [comment]
> You can do also like this: open the folder of the mod/datapack and go to data/ddd/worldgen/structure_set. Here you can edit "dddungeons" and "dddtowers" as you like

I might mess up the code structure so I'll just wait for the update. I tried creating a datapack that would be able to mine bedrock and somehow I cant get it right hahaha. I wish I could make my own structure mod too yet needed some help.

**Comment by Caesius-Leo** [comment]
Ok i posted the new version! It should be better now! Don't give up for the datapack, with time and patience you will improve :) . There are a lot of tutorial on the internet if you need help. For example for structure thi is one: https://www.youtube.com/watch?v=s3y4aWVZJeo 
For sure you need hard work!

**Comment by makumaku1974** [comment]
Thank you very much i'll be closing this now

**Comment by Caesius-Leo** [comment]
> > ok, have fun :) use sparce structures for now I'll do an update asap
> 
> This is actually a great structure mod. Does is have a custom loot tables because it seems that modded items are not present. I dont mean it's bad but it's a better exchange from Battle Towers.

Sorry but my english have some limitation, I think I understand that you like it but the are no modded items. This is correct because this project is planned to work in vanilla minecraft to improve the vanilla experience, the mod version is used to make automatic the loading of the datapack in every new world
